import { Link } from 'react-router-dom';
import { ArrowRight20Regular, ArrowUpRight20Regular, ArrowRight24Regular, CalendarLtr24Regular, ChatMultiple20Regular, Lightbulb24Regular, Sparkle24Regular } from '@fluentui/react-icons';
import { ProgressBar } from '@fluentui/react-components';
import { useApiQuery } from '@cvs-garage/api-client';
import { ServiceMark, SectionHeading, LoadingState, ErrorState, Person, StatusBadge, dateLabel, ColorRail, EmptyState } from '@cvs-garage/ui';
import type { Overview, Session } from '@cvs-garage/contracts';
import { services } from './services';
import { EventPoster } from './Landing';

export function Home({ session }: { session: Session }) {
  const query = useApiQuery<Overview>('/overview'); const overview = query.data;
  const firstName = session.member?.displayName.split(' ')[0];
  return <main id="main-content" className="home-page"><header className="home-heading"><div><div className="eyebrow">Your campus, in one place</div><h1>{firstName ? `Good to see you, ${firstName}.` : 'A little more connected.'}</h1><p>{firstName ? 'Pick up where you left off. Or find something new.' : 'Good people. Interesting ideas. Plenty of places to begin.'}</p></div><time className="home-date" dateTime={new Date().toISOString().slice(0, 10)}><CalendarLtr24Regular /><span>{dateLabel(new Date().toISOString(), { weekday: 'long' })}<strong>{dateLabel(new Date().toISOString(), { day: 'numeric', month: 'long', year: 'numeric' })}</strong></span></time></header>
    <section className="home-feature"><div className="feature-copy"><span className="feature-label"><Sparkle24Regular /> There’s room for your next thing.</span><h2>Big things start<br />with a small <span>“what if.”</span></h2><p>An idea, a question, a half-finished sketch.<br />Bring it to the Garage. See what happens next.</p><Link to="/ideas" className="feature-cta">Explore the Idea Centre <ArrowRight20Regular /></Link></div><div className="feature-note"><div className="feature-note-top"><Lightbulb24Regular /><span>FROM THOUGHT<br />TO SOMETHING</span></div><div className="note-steps"><div><span>01</span> Find a little inspiration</div><div><span>02</span> Find your kind of people</div><div><span>03</span> Make a first version <ArrowUpRight20Regular /></div></div><div className="feature-note-bottom">You don’t have to figure it out alone.</div></div><ColorRail /></section>
    <section className="home-spaces"><SectionHeading title="Where would you like to go?" /><div className="home-service-grid">{services.map((s) => <Link to={s.path} key={s.path} data-service={s.area}><ServiceMark area={s.area} /><strong>{s.title}</strong><span>{s.verb}</span><ArrowUpRight20Regular className="service-shortcut-arrow" /></Link>)}</div></section>
    {query.isPending ? <LoadingState /> : query.error ? <ErrorState error={query.error} retry={() => void query.refetch()} /> : <>
      <div className="home-columns"><div className="home-main-column"><section><SectionHeading title="Coming up on campus" description="A few good reasons to be there." to="/events" linkText="All events" /><div className="home-event-grid">{overview?.events.slice(0, 2).map((event, i) => <Link key={event.id} to={`/events/${event.id}`} className="home-event-card"><EventPoster event={event} index={i} compact /><div className="home-event-content"><span className="event-category">{event.category} <i /> {event.mode}</span><h3>{event.title}</h3><div className="row-between"><span>{dateLabel(event.startsAt)} · {event.location.venue ?? event.location.platformName}</span><ArrowUpRight20Regular /></div></div></Link>)}</div>{!overview?.events.length && <EmptyState title="A little space in the calendar" description="Published campus events will appear here." />}</section>
        <section className="home-projects"><SectionHeading title={session.member ? 'A little progress, every day' : 'Made around here'} description={session.member ? 'Your projects, right where you left them.' : 'A few things the campus has been building.'} to={session.member ? '/projects?tab=mine' : '/projects'} linkText="All projects" />{overview?.projects.length ? overview.projects.slice(0, 2).map((project) => {
          const completed = project.milestones.filter((m) => m.status === 'completed').length;
          return <Link key={project.id} to={`/projects/${project.id}`} className="home-project-row"><ServiceMark area="projects" /><div className="home-project-info"><h3>{project.title}</h3><span>{project.teamName} · {project.status === 'completed' ? 'Published showcase' : `${completed} of 6 milestones complete`}</span>{project.milestones.length > 0 && <ProgressBar value={completed / 6} aria-label={`${completed} of 6 milestones complete`} />}</div><ArrowUpRight20Regular /></Link>;
        }) : <div className="soft-panel"><h3>Your next project starts with a pitch.</h3><p className="muted">Put your idea into words. A team can come next.</p><Link to="/projects?tab=pitches" className="text-link">Explore project pitches <ArrowRight20Regular /></Link></div>}</section>
      </div><aside className="home-side-column"><section className="campus-pulse"><div className="eyebrow">The campus pulse <span className="pulse-dot" /></div><h2>Small starts.<br />Shared momentum.</h2><div className="pulse-stats"><div><strong>{overview?.counts.projects}</strong><span>projects shared</span></div><div><strong>{overview?.counts.ideas}</strong><span>ideas taking shape</span></div><div><strong>{overview?.counts.events}</strong><span>events to explore</span></div><div><strong>{overview?.counts.members}</strong><span>people to meet</span></div></div>{overview?.demo && <span className="pulse-footnote">A snapshot of this fictional campus.</span>}</section>
      <section className="home-conversations"><SectionHeading title="Over in the Forum" to="/forum" linkText="Join in" />{overview?.discussions.map((post) => <Link className="conversation-preview" to={`/forum/${post.id}`} key={post.id}><span className="conversation-type">{post.postType === 'question' ? 'A good question' : post.postType === 'idea' ? 'A new possibility' : 'Around the table'}</span><h3>{post.title}</h3><div className="row-between"><span>{post.author.displayName}</span><span><ChatMultiple20Regular /> {post.replyCount}</span></div></Link>)}</section></aside></div>
      <section className="home-ideas"><SectionHeading title="An idea looking for its people" description="You might be the missing piece." to="/ideas" linkText="Find your next idea" /><div className="grid grid-3">{overview?.ideas.map((idea) => <Link key={idea.id} to={`/ideas/${idea.id}`} className="idea-preview"><span className="idea-preview-code">{idea.ticketCode} <ArrowUpRight20Regular /></span><h3>{idea.title}</h3><p>{idea.tagline}</p><div className="row-between"><span>{idea.track.name}</span><span>{idea.targetTeamSize - idea.teamCount} open spots</span></div></Link>)}</div></section>
    </>}
    <footer className="workspace-footer"><span>A shared campus, made a little more connected.</span><Link to="/">The story of the Garage <ArrowUpRight20Regular /></Link></footer>
  </main>;
}
