import { Link } from 'react-router-dom';
import { ArrowRight24Regular, ArrowUpRight20Regular, ArrowDown20Regular, Sparkle24Regular, PeopleTeam24Regular, CalendarLtr24Regular, LeafThree24Regular, Mic24Regular, Code24Regular } from '@fluentui/react-icons';
import { ColorRail, ServiceMark, dateLabel, LoadingState, ErrorState, SectionHeading } from '@cvs-garage/ui';
import { useApiQuery } from '@cvs-garage/api-client';
import type { CampusEvent, Overview, Session } from '@cvs-garage/contracts';
import { Brand, ThemeSwitch } from './Shell';
import { services } from './services';

export function EventPoster({ event, index = 0, compact = false }: { event: CampusEvent; index?: number; compact?: boolean }) {
  const identity = ['projects', 'events', 'leaderboards', 'forum'][index % 4];
  const Icon = event.category === 'Cultural' ? Mic24Regular : event.category === 'Technical' ? Code24Regular : index % 2 ? LeafThree24Regular : Sparkle24Regular;
  return <div className={`event-poster ${compact ? 'compact' : ''}`} data-service={identity} aria-hidden><div className="poster-top"><span>THE GARAGE<br />COLLECTIVE</span><span>{event.mode}</span></div><Icon className="poster-symbol" /><div className="poster-title">{event.title}</div><div className="poster-bottom"><span>{dateLabel(event.startsAt, { day: '2-digit', month: 'short' }).toUpperCase()}</span><span>{dateLabel(event.startsAt, { hour: 'numeric', minute: '2-digit' })}</span></div></div>;
}

export function Landing({ session }: { session: Session }) {
  const overview = useApiQuery<Overview>('/overview');
  const featured = overview.data?.events[0];
  return <div className="landing"><header className="landing-nav"><Brand compact /><nav aria-label="Landing page"><a href="#spaces">The spaces</a><a href="#whats-on">What’s on</a><a href="#made-here">Made here</a></nav><div className="landing-nav-actions"><ThemeSwitch /><Link to="/home" className="outline-link">Enter the Garage <ArrowUpRight20Regular /></Link></div></header><main id="main-content">
    <section className="landing-hero"><div className="hero-copy"><div className="eyebrow"><span className="tiny-square" /> A shared campus. A little more connected.</div><h1>A little curiosity.<br />A lot of<br /><span>possibility.</span></h1><p>For the things you want to build.<br />The people you haven’t met.<br />And the ideas that won’t leave you alone.</p><div className="hero-actions"><Link to="/home" className="primary-link">Find your place <ArrowRight24Regular /></Link><a href="#spaces" className="text-link">Take a look around <ArrowDown20Regular /></a></div><div className="hero-footnote"><PeopleTeam24Regular /><span>Six spaces. One campus. Room for everyone.</span></div></div>
      <div className="hero-board" aria-label="A glimpse of life at the Garage"><div className="board-heading"><span>ON THE CAMPUS PINBOARD</span><span>THIS WEEK ↗</span></div>
        <Link to={featured ? `/events/${featured.id}` : '/events'} className="pinboard-event"><span className="paper-tape" aria-hidden />{featured ? <EventPoster event={featured} /> : <div className="pinboard-placeholder"><CalendarLtr24Regular /><strong>There’s a place<br />for you here.</strong><span>Discover campus events</span></div>}<div className="pinboard-caption"><span>{featured ? 'Something worth showing up for.' : 'Make room for a new experience.'}</span><ArrowUpRight20Regular /></div></Link>
        <Link to="/ideas" className="pinboard-note"><span className="note-label">AN OPEN INVITATION</span><span className="note-icon"><Sparkle24Regular /></span><strong>That “what if”<br />is worth<br />exploring.</strong><span className="note-footer">Find an idea to make your own <ArrowUpRight20Regular /></span></Link>
        <div className="board-bottom"><span>Not another noticeboard.</span><span>A place to begin.</span></div>
      </div>
    </section>
    <div className="landing-manifesto"><p>A campus is more than a place you go.<br /><strong>It’s what you make of it, together.</strong></p><ColorRail /><span>Built around your everyday.<br />Open to your next big thing.</span></div>
    <section id="spaces" className="landing-section spaces-section"><div className="landing-section-heading"><div><div className="eyebrow">Make yourself at home</div><h2>Different doors.<br />One shared space.</h2></div><p>Start with what interests you.<br />See where it takes you.</p></div><div className="spaces-grid">{services.map((s) => <Link key={s.area} to={s.path} className="space-tile" data-service={s.area}><div className="row-between"><ServiceMark area={s.area} /><span className="space-number">{s.number}</span></div><span className="space-name">{s.title}</span><h3>{s.verb}</h3><p>{s.description}</p><span className="space-arrow"><ArrowUpRight20Regular /></span></Link>)}</div></section>
    <section id="whats-on" className="landing-section events-section"><div className="landing-section-heading"><div><div className="eyebrow">A good reason to step out</div><h2>See you around?</h2></div><Link to="/events" className="text-link">Everything coming up <ArrowUpRight20Regular /></Link></div>
      {overview.isPending ? <LoadingState label="Finding what’s on campus" /> : overview.error ? <ErrorState error={overview.error} retry={() => void overview.refetch()} /> : <div className="landing-events">{overview.data?.events.map((event, i) => <Link to={`/events/${event.id}`} key={event.id} className="landing-event"><EventPoster event={event} index={i} /><div className="event-summary"><span className="eyebrow">{event.category} · {event.mode}</span><h3>{event.title}</h3><p>{event.shortSummary}</p><span className="text-link">Save yourself a spot <ArrowUpRight20Regular /></span></div></Link>)}</div>}
    </section>
    <section id="made-here" className="landing-section made-section"><div className="made-copy"><div className="eyebrow">Not just ideas. Real things.</div><h2>Made here.<br /><span>By people like you.</span></h2><p>Small starts, late-night iterations, and a few things that turned out better than expected. Take a look at what our campus is making.</p><Link className="primary-link" to="/projects">Explore the showcase <ArrowRight24Regular /></Link></div><div className="made-list">{overview.data?.projects.length ? overview.data.projects.map((project, i) => <Link to={`/projects/${project.id}`} key={project.id}><span className="made-index">0{i + 1}</span><div><span className="eyebrow">{project.category}</span><h3>{project.title}</h3><p>{project.description}</p></div><ArrowUpRight20Regular /></Link>) : <div className="made-empty"><ServiceMark area="projects" large /><h3>Your next project could be right here.</h3><p>Start with a question. Find your team. Make a first version.</p></div>}</div></section>
    <section className="landing-invitation"><div className="eyebrow">Come as you are</div><h2>You don’t need a big idea.<br />Just a place to start.</h2><Link to={session.member ? '/home' : '/sign-in'} className="invitation-link">{session.member ? 'Back to your campus' : session.demoAvailable ? 'Try the campus demo' : 'Join your campus'} <ArrowRight24Regular /></Link><ColorRail /></section>
  </main><footer className="landing-footer"><Brand compact /><span>For the makers, the doers, the quietly curious.</span><div><Link to="/home">Campus home</Link><a href="#spaces">Explore the spaces</a></div></footer></div>;
}
